// <auto-generated />
namespace purrfect_blog_starter_1757957984.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SeedTestPosts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedTestPosts));
        
        string IMigrationMetadata.Id
        {
            get { return "202510010749395_SeedTestPosts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
